version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.production  # Load environment file
    volumes:
      - .:/app
    restart: unless-stopped